language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: improbable-keanu
script: deployment/buildAndDeploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_eec04b57ffc0_key -iv $encrypted_eec04b57ffc0_iv
  -in deployment/secret-keys-keanu.gpg.enc -out deployment/secret-keys-keanu.gpg -d
