language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "improbable-keanu"
    token:
      secure: "Cs6wJeWkTXoOzEh4Sjiz/Er0A9f7kSGzUw+VfzSeYTQUqNnmPcX1+rNC9VMShyHTJt8syF4V9ax3/yWuzSAob87W1DH6NnwVNDbvIbImSvrEd8pf8r6k4DCAqlWq09gSr5os4zloL+Rmy5kty3WSWxuO13Bn9/oygF7l+d8UahtNdL8GS20gmNeBp/w2G66jK07/mlrKjsQ6QQRYNpmoGeAmXWZad/UnaeE8BlJ0I2yYRctSELsTpJEJtODr/tIihtiLxGAaBmWtuEavqb1lDdjFpZ1dAxYA2eD5uN/pbCZcghK6DUJPzxAg/SpZUxmYUMHOLXS7fjGGDRmHAUEF4T1H50iiXPQlnhlW/DMN2tfJX92qJqO2gLI6L05A/Kn4ZTxQ5Z4KMikxfRGbN125e0XlKnyg9Axvm5d3EMYr511hBwjHx2u5fKvKVMhSzWW7sy7tTvXXScUE2rDAI6n4rc48CMzNcE7ea4Fta5UWyjckPmuCZrihodMJbEeiyNUgxLk4fZ+Wek/0oiN8odv8VttK72RdjHIJkR4c8wdiIKC5iFcioiR7aVOXAuPx4H+8gAvCZscg96PXuZVCay67eDFPigtTnHnNk0thcgL5aI7WmdkP52dXkksvagJG6gO8b1aD2sYD1h8zpL9IhH4iVcXhsdMi7P/MHwxdL0sz2Sc="
script:
  - sonar-scanner