language: java
jdk:
  - oraclejdk8
python:
  - 3.6
addons:
  sonarcloud:
    organization: "improbable-keanu"
script:
  - ./gradlew clean build -i
  - 'if [[ ! -z $SONAR_TOKEN ]]; then sonar-scanner; fi'
