language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: improbable-keanu
script:
- "./gradlew uploadArchives -PnexusUser=$NEXUS_USER -PnexusPassword=$NEXUS_PASSWORD -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=deployment/secret-keys-keanu.gpg"
- if [[ ! -z $SONAR_TOKEN ]]; then sonar-scanner; fi
before_install:
- openssl aes-256-cbc -K $encrypted_eec04b57ffc0_key -iv $encrypted_eec04b57ffc0_iv
  -in secret-keys-keanu.gpg.enc -out secret-keys-keanu.gpg -d
