version: 1.0.{build}
environment:
  PYTHON: "C:\\Python36-x64"
install:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
build_script:
- cmd: ./gradlew.bat clean keanu-python:build -i --stacktrace --debug
